# Inserts a blank line between shell prompts
add_newline = false

# Make prompt a single line instead of two lines
# [line_break]
# disabled = true

# A minimal left prompt
format = """$character"""

# move the rest of the prompt to the right
right_format = """$all"""
